// flovira-designer/vue/src/components/design/common/vue/LifecycleEditor.vue
<template>
  <section class="form-section" :aria-label="nodeType == null ? '流程回调' : '节点回调'">
    <div class="section-title">{{ nodeType == null ? '流程回调' : '节点回调' }}</div>
    <p v-if="error" role="alert">{{ error }}</p>
    <fieldset v-for="(row, index) in config.subscriptions" :key="index" :disabled="disabled">
      <wf-form-item label="监听器 Bean 名"><wf-input :model-value="row.code" :disabled="disabled" @update:model-value="patch(index, { code: $event })" /></wf-form-item>
      <wf-form-item label="回调时机"><wf-select :model-value="row.point" :disabled="disabled" @update:model-value="changePoint(index, $event)">
        <wf-option v-for="[point, label] in points" :key="point" :value="point" :label="label" />
      </wf-select></wf-form-item>
      <wf-form-item label="执行阶段"><wf-select :model-value="row.phase" :disabled="disabled" @update:model-value="patch(index, { phase: $event })">
        <wf-option value="IN_TRANSACTION" label="事务内" />
        <wf-option v-if="!row.point.startsWith('BEFORE_')" value="AFTER_COMMIT" label="提交后" />
      </wf-select></wf-form-item>
      <wf-form-item label="执行顺序"><wf-input type="number" :model-value="String(row.order)" :disabled="disabled" @update:model-value="patch(index, { order: Number($event) })" /></wf-form-item>
      <wf-form-item label="参数"><wf-input :model-value="row.parameters || ''" :disabled="disabled" @update:model-value="patch(index, { parameters: $event })" /></wf-form-item>
      <wf-button :disabled="disabled" @click="save(config.subscriptions.filter((_, i) => i !== index))">删除回调</wf-button>
    </fieldset>
    <wf-button :disabled="disabled || !points.length || invalidJson" @click="save([...config.subscriptions, { code: '', point: points[0][0], phase: 'IN_TRANSACTION', order: 0 }])">添加回调</wf-button>
  </section>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { lifecyclePoints, parseLifecycle, validateLifecycle } from '@/data/lifecycle'
import type { LifecyclePoint, LifecycleSubscription } from '@/data/lifecycle'
const props = defineProps<{ modelValue?: string; nodeType?: string; disabled?: boolean }>()
const emit = defineEmits<{ (e: 'update:modelValue', value: string): void }>()
const parsed = computed(() => {
  try { return { config: parseLifecycle(props.modelValue), error: '' } }
  catch (error) { return { config: { schemaVersion: 1 as const, subscriptions: [] }, error: String(error) } }
})
const config = computed(() => parsed.value.config)
const invalidJson = computed(() => Boolean(parsed.value.error))
const error = computed(() => {
  if (parsed.value.error) return parsed.value.error
  try { validateLifecycle(config.value, props.nodeType); return '' } catch (error) { return String(error) }
})
const points = computed(() => lifecyclePoints(props.nodeType))
const save = (subscriptions: LifecycleSubscription[]) => emit('update:modelValue', JSON.stringify({ schemaVersion: 1, subscriptions }))
const patch = (index: number, value: Partial<LifecycleSubscription>) => save(config.value.subscriptions.map((row, i) => i === index ? { ...row, ...value } : row))
const changePoint = (index: number, point: LifecyclePoint) => patch(index, { point, phase: point.startsWith('BEFORE_') ? 'IN_TRANSACTION' : config.value.subscriptions[index].phase })
</script>

<style scoped>
fieldset {
  min-width: 0;
  margin: 0 0 24px;
  padding: 0 0 20px;
  border: 0;
  border-bottom: 1px solid var(--wf-border-color, #dcdfe6);
}
[role="alert"] { color: var(--wf-danger, #f56c6c); }
</style>

// flovira-designer/react/src/LifecycleEditor.tsx
import { lifecyclePoints, lifecycleValue, parseLifecycle, validateLifecycle, withLifecycle } from './lifecycle'
import type { LifecycleSubscription } from './lifecycle'
import type { DesignerUiAdapter } from './types'

export function LifecycleExtEditor({ ext, onChange, ...props }: {
  ext?: unknown; nodeType?: string; ui: DesignerUiAdapter; disabled: boolean; onChange(ext: string): void
}) {
  let value
  try { value = lifecycleValue(ext) } catch (error) { return <p role="alert">{String(error)}</p> }
  return <LifecycleEditor {...props} value={value} onChange={value => onChange(withLifecycle(ext, parseLifecycle(value)))} />
}

export function LifecycleEditor({ value, nodeType, ui, disabled, onChange }: {
  value?: string; nodeType?: string; ui: DesignerUiAdapter; disabled: boolean; onChange(value: string): void
}) {
  const { Field, Input, Select, Button } = ui
  let config
  try { config = parseLifecycle(value) } catch (error) { return <p role="alert">{String(error)}</p> }
  let error = ''
  try { validateLifecycle(config, nodeType) } catch (failure) { error = String(failure) }
  const options = lifecyclePoints(nodeType).map(([value, label]) => ({ value, label }))
  const change = (index: number, patch: Partial<LifecycleSubscription>) => onChange(JSON.stringify({ ...config,
    subscriptions: config.subscriptions.map((row, i) => i === index ? { ...row, ...patch } : row),
  }))
  return <section aria-label={nodeType === undefined ? '流程回调' : '节点回调'} className="frd-settings-group">
    <h4>{nodeType === undefined ? '流程回调' : '节点回调'}</h4>
    {error && <p role="alert">{error}</p>}
    {config.subscriptions.map((row, index) => <fieldset className="frd-lifecycle-row" key={index} disabled={disabled}>
      <Field label="监听器 Bean 名"><Input ariaLabel={`监听器 Bean 名 ${index + 1}`} value={row.code} disabled={disabled}
        onValueChange={code => change(index, { code })} /></Field>
      <Field label="回调时机"><Select ariaLabel={`回调时机 ${index + 1}`} value={row.point} disabled={disabled} options={options}
        onValueChange={point => change(index, { point: point as LifecycleSubscription['point'],
          phase: point.startsWith('BEFORE_') ? 'IN_TRANSACTION' : row.phase })} /></Field>
      <Field label="执行阶段"><Select ariaLabel={`执行阶段 ${index + 1}`} value={row.phase} disabled={disabled}
        options={[{ value: 'IN_TRANSACTION', label: '事务内' }, ...(!row.point.startsWith('BEFORE_') ? [{ value: 'AFTER_COMMIT', label: '提交后' }] : [])]}
        onValueChange={phase => change(index, { phase: phase as LifecycleSubscription['phase'] })} /></Field>
      <Field label="执行顺序"><Input ariaLabel={`执行顺序 ${index + 1}`} type="number" value={String(row.order)} disabled={disabled}
        onValueChange={order => change(index, { order: Number(order) })} /></Field>
      <Field label="参数"><Input ariaLabel={`监听参数 ${index + 1}`} value={row.parameters || ''} disabled={disabled}
        onValueChange={parameters => change(index, { parameters })} /></Field>
      <Button disabled={disabled} onPress={() => onChange(JSON.stringify({ ...config, subscriptions: config.subscriptions.filter((_, i) => i !== index) }))}>删除回调</Button>
    </fieldset>)}
    <Button disabled={disabled || !options.length} onPress={() => onChange(JSON.stringify({ ...config,
      subscriptions: [...config.subscriptions, { code: '', point: options[0].value, phase: 'IN_TRANSACTION', order: 0 }],
    }))}>添加回调</Button>
  </section>
}
